---
# =============================================================================
# Ansible Role: Logrotate - Tasks: Configuration
# =============================================================================
# Manages the main /etc/logrotate.conf configuration file.
# =============================================================================

- name: Logrotate | configure | Render main /etc/logrotate.conf
  become: true
  ansible.builtin.template:
    src: "logrotate.conf.j2"
    dest: "{{ logrotate_main_config_path }}"
    owner: root
    group: root
    mode: "0644"
    validate: "logrotate -d -s {{ logrotate_status_file }} %s"
    backup: true
