---
# =============================================================================
# Ansible Role: Logrotate - Tasks: Installation
# =============================================================================
# Installs the logrotate package.
# =============================================================================

- name: Logrotate | install | Ensure logrotate present
  ansible.builtin.package:
    name: "{{ logrotate_package_name }}"
    state: present
  register: __logrotate_package_result
  retries: 3
  delay: 5
  until: __logrotate_package_result is succeeded
