---
# =============================================================================
# Ansible Role: logrotate - Main Tasks
# =============================================================================
# This is the main task file for the logrotate role. It orchestrates the
# execution of all role components in the correct order. Each task is tagged
# appropriately to allow for selective execution.
#
# Flow:
# 1. Load OS-specific variables
# 2. Validate role requirements and variables
# 3. Install logrotate
# 4. Configure main logrotate.conf
# 5. Manage drop-in rules under /etc/logrotate.d
#    5.1 Apply present rules (per-rule include)
#    5.2 Remove absent rules (per-rule include)
# 6. Verify configuration (dry-run)
# =============================================================================

# -----------------------------------------------------------------------------
# 1. OS-Specific Variables
# -----------------------------------------------------------------------------
- name: logrotate | include_vars | Gather OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
        - "main.yml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - always
    - setup
    - init

# -----------------------------------------------------------------------------
# 2. Variable Validation
# -----------------------------------------------------------------------------
- name: logrotate | assert | Validate role variables and requirements
  ansible.builtin.include_tasks: assert.yml
  run_once: true
  tags:
    - always
    - validate

# -----------------------------------------------------------------------------
# 3. Package Installation
# -----------------------------------------------------------------------------
- name: logrotate | install | Install dependencies
  ansible.builtin.include_tasks: install.yml
  when: >
    logrotate_role_action in ['all', 'install']
  tags:
    - setup
    - install

# -----------------------------------------------------------------------------
# 4. Main Configuration
# -----------------------------------------------------------------------------
- name: logrotate | configure | Configure main logrotate.conf
  ansible.builtin.include_tasks: configure.yml
  when: >
    logrotate_role_action in ['all', 'configure'] and
    logrotate_manage_main_conf
  tags:
    - setup
    - configure
    - config

# -----------------------------------------------------------------------------
# 5. Drop-in Rules Management (Optional)
# -----------------------------------------------------------------------------
- name: logrotate | rules | Apply present rules
  ansible.builtin.include_tasks: rules.yml
  vars:
    rule: "{{ item }}"
  loop: "{{ (logrotate_rules | selectattr('state', 'defined') | selectattr('state', 'equalto', 'present') | list)
           + (logrotate_rules | rejectattr('state', 'defined') | list) }}"
  loop_control:
    label: "{{ item.name }}"
  when: >
    logrotate_role_action in ['all', 'logrotate'] and
    logrotate_rules | length > 0
  tags:
    - config
    - logrotate

- name: logrotate | rules | Remove absent rules
  ansible.builtin.include_tasks: rules.yml
  vars:
    rule: "{{ item }}"
  loop: "{{ logrotate_rules | selectattr('state', 'defined') | selectattr('state', 'equalto', 'absent') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when: >
    logrotate_role_action in ['all', 'logrotate'] and
    logrotate_rules | length > 0
  tags:
    - config
    - logrotate

# -----------------------------------------------------------------------------
# 6. Configuration Verification (Optional)
# -----------------------------------------------------------------------------
- name: logrotate | verify | Verify configuration (dry-run)
  ansible.builtin.include_tasks: verify.yml
  when: >
    logrotate_role_action in ['all', 'configure', 'logrotate']
  tags:
    - test
    - verify
